---
- name: setup zsh shell
  become: "{{ is_root }}"
  block:
    - name: setup zsh
      block:
      - name: zsh check
        become: true
        apt:
          name: 
            - zsh
            - git
            - gawk
          state: latest

      - name: copy base .zshrc
        copy: 
          src: "{{ role_path }}/files/config/zsh/.zshrc"
          dest: $HOME/.zshrc

      - name: add zsh history
        file: 
          path: $HOME/.zsh_history
          state: touch

      - name: zsh change shell
        become: true
        user: 
          name: "{{ user }}"
          shell: /usr/bin/zsh

    - name: setup zplug
      block:
        - name: zsh install zplug
          shell: curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
          args:
            creates: $HOME/.zplug

        - name: ensure zsh zplug .config dir 
          file:
            path: $HOME/.config/zplug
            state: directory

        - name: zsh copy zplug config
          copy: 
            src: "{{ role_path }}/files/config/zsh/zplug.sh"
            dest: $HOME/.config/zplug/config.sh
            force: true

        - name: zsh add zplug into .zshrc
          lineinfile:
            dest: $HOME/.zshrc
            line: . "$HOME/.config/zplug/config.sh"
            regexp: \. "\$HOME\/\.config\/zplug\/config\.sh"
            state: present

    - name: setup starship
      block:
      - name: zsh install starship
        become: true
        shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
        args:
          creates: /usr/local/bin/starship

      - name: zsh add starship to .zshrc
        lineinfile:
          dest: $HOME/.zshrc
          line: eval "$(starship init zsh)"
          regexp: eval "\$\(starship init zsh\)"
          state: present

      - name: zsh add starship config
        vars: 
          config_dir: $HOME/.config
        block:

          - name: ensure starship config folder exists
            file: 
              path: "{{ config_dir }}"
              state: directory
        
          - name: copy starship config
            copy:
              src: "{{ role_path }}/files/config/starship/config.toml"
              dest: "{{ config_dir }}/starship.toml"
              force: true
    
    - name: atuin shell history
      block: 
        - name: install atuin
          become: true
          shell: curl https://raw.githubusercontent.com/ellie/atuin/main/install.sh | bash
          args:
            creates: /usr/bin/atuin

        - name: add atuin to .zshrc
          lineinfile:
            dest: $HOME/.zshrc
            line: eval "$(atuin init zsh)"
            regexp: eval "\$\(atuin init zsh\)"
            state: present

