---
- name: setup apt apps
  become: true
  apt:
    name:
      # CLI
      - build-essential
      - htop
      - tmux
      - exa
      - neovim
      - zsh
      - autojump
      - trash-cli
      - btop
      - fzf
      - tldr

      # GUI
      - virtualbox

      # others
      - tlp
      - tlp-rdw
    state: latest

- name: autojump add to {{ shellrc }}
  become: "{{ is_root }}"
  lineinfile:
    dest: "{{ shellrc }}"
    line: . /usr/share/autojump/autojump.sh
    regexp: \. \/usr\/share\/autojump\/autojump\.sh
    state: present

- name: set exa aliases
  become: "{{ is_root }}"
  block:
    - name: exa alias ls
      lineinfile:
        dest: "{{ shellrc }}"
        line: alias ls="exa"
        regexp: alias ls="exa" 
        state: present

    - name: exa alias ll
      lineinfile:
        dest: "{{ shellrc }}"
        line: alias ll="exa -l"
        regexp: alias ll="exa -l"
        state: present

- name: tlp enable
  become: true
  service:
    name: tlp
    state: started
    enabled: true

- name: trash cli
  become: "{{ is_root }}"
  lineinfile:
    dest: "{{ shellrc }}"
    line: alias rm="trash-put -iv"
    regexp: alias rm="trash-put -iv"
    state: present