---
# setup vscode using apt repo because it's error frequently
# https://flathub.org/

- name: setup flatpak
  become: "{{ is_root }}"
  when: use_gui_apps
  vars:
    autostart_dir: $HOME/.config/autostart
  block:
  - name: flatpak install for ubuntu
    when: ansible_distribution == "Ubuntu"
    become: true
    block:
      - name: flatpak install ubuntu
        apt:
          name: flatpak
          state: latest
      - name: flatpak add https://flathub.org/
        community.general.flatpak_remote: 
          name: flathub
          flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
          state: present

  - name: flatpak install apps
    become: true
    flatpak:
      name:
        - com.brave.Browser
        - com.getpostman.Postman
        - nz.mega.MEGAsync
        - com.mongodb.Compass
        - com.redis.RedisInsight
        - md.obsidian.Obsidian
      state: present

  - name: flatpak ensure config dir
    file: 
      path: "{{ autostart_dir }}"
      state: directory

  - name: flatpak add autostart
    copy: 
      src: "{{ item.src }}"
      dest: "{{ autostart_dir }}/{{ item.filename }}"
      force: true
    with_items:
      - src: "{{ role_path }}/files/config/mega/autostart.desktop"
        filename: mega.desktop