---
# setup vscode using apt repo because it's error frequently
# https://flathub.org/

- name: setup flatpak apps
  become: true
  flatpak:
    name:
      - com.brave.Browser
      - com.getpostman.Postman
      - nz.mega.MEGAsync
      - com.mongodb.Compass
    state: present
