---
- name: terraform install
  become: true
  vars:
    apt_key_path: /usr/share/keyrings/hashicorp-archive-keyring.asc
  block:
    - name: terraform get upstream distribution codename (ubuntu codename)
      when: is_mint
      shell: . /etc/upstream-release/lsb-release && echo "$DISTRIB_CODENAME"
      register: codename_mint

    - name: terraform get distribution codename
      when: is_ubuntu
      shell: . /etc/os-release && echo "$VERSION_CODENAME"
      register: codename_ubuntu

    - name: terraform set codename
      set_fact:
        distribution_codename: "{{ codename_mint.stdout if is_mint else codename_ubuntu.stdout }}"

    - name: terraform get apt key
      get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: "{{ apt_key_path }}"

    - name: terraform add repository
      apt_repository:
        repo: deb [signed-by={{ apt_key_path }}] https://apt.releases.hashicorp.com {{ distribution_codename }} main
        filename: hashicorp
        state: present
    
    - name: terraform install
      apt:
        name: terraform
        state: latest