---
- name: apt update
  become: true
  apt:
    update_cache: true

- name: load group tasks
  include_tasks: "{{ group_task }}"
  loop_control:
    loop_var: group_task
  with_items: 
    - services/_main.yml
    - settings/_main.yml
    - softwares/_main.yml