---
- name: setup CLI apps
  become: true
  apt:
    name:
      - build-essential
      - htop
      - tmux
      - exa
      - neovim
      - zsh
      - autojump
    state: latest
    update_cache: true

- name: autojump add to {{ shellrc }}
  become: false
  lineinfile:
    dest: "{{ shellrc }}"
    line: . /usr/share/autojump/autojump.sh
    regexp: \. \/usr\/share\/autojump\/autojump\.sh
    state: present