---
# https://docs.ansible.com/ansible/latest/collections/community/general/ssh_config_module.html
- name: setup ssh
  become: false
  vars:
    dir: ~/.ssh
    configs:
    - host: github.com
      hostname: github.com
      file: id_rsa_github
    - host: gitlab.com
      hostname: gitlab.com
      file: id_rsa_gitlab
    - host: phabricator.sirclo.com
      hostname: phabricator.sirclo.com
      file: id_rsa_phabricator
  
  block:
    - name: ssh install prerequisite
      become: true
      apt: 
        name:
          - git
          - python3-paramiko
        state: latest

    - name: ssh make dir
      file:
        path: "{{ dir }}"
        state: directory

    - name: ssh generate
      openssh_keypair:
        path: "{{ dir }}/{{ item.file }}"
        type: rsa
        size: 4096
        state: present
        force: no
      with_items: "{{ configs }}"

    - name: ssh config
      community.general.ssh_config:
        host: "{{ item.host }}"
        hostname: "{{ item.hostname }}"
        user: "{{ user }}"
        identity_file: "{{ dir }}/{{ item.file }}"
      with_items: "{{ configs }}"
