galaxy_info:
  author: labasubagia22@gmail.com
  description: development environment 
  license: MIT

  min_ansible_version: "2.1"
  
  platforms:
    - name: Ubuntu
      versions:
        - jammy
  
  galaxy_tags: []

dependencies: []
