name: Test ansible on ubuntu

on:
  push:
    branches:
      - main

jobs:
  Test: 
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Requirements
        run: make install-requirements

      - name: Run
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: ansible-playbook -i "localhost," playbook.yml --extra-vars="dev_user=root" -u root