name: Test ansible on ubuntu

on:
  push:
    branches:
      - main

jobs:
  Test: 
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible
      
      - name: Install Requirements
        run: make install-requirements

      - name: Run
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: ansible-playbook -i "localhost," playbook-root.test.yml -u root